export const padding = 3;
export const horizontalPadding = 12;
export const blockCornerRadius = 10;
export const blockStrokeWidth = 2;
export const highlightStrokeWidth = 4;
export const placeholderWidth = 100;
export const placeholderHeight = 72;
export const placeholderCornerRadius = 36;
export const labelFontSize = 32;
export const dropdownHeight = 60;
export const bubbleColor = "#121212";
export const resolvedGapRadius = 12;

export const sidebarPadding = { top: 100, bottom: 100, right: 80, left: 12 };
export const blockListSpacing = 20;
export const blockListFontSize = 26;
export const scrollMomentumExtent = 20;
export const initialVisibleCount = 5;
export const visiblilityIncrement = 5;